authors:
  leonardo:
    name: Leonardo Pangaio
    description: Curioso
    avatar: https://github.com/leonardopangaio.png
    url: https://linkedin.com/in/leonardo-pangaio
  luciana:
    name: Luciana Sampaio
    description: Engenheira de Dados
    avatar: https://github.com/luasampaio.png
    url: https://www.linkedin.com/in/luciana-sampaio/