authors:
  leonardo:
    name: Leonardo Pangaio
    description: Curioso
    avatar: https://github.com/leonardopangaio.png
    url: https://linkedin.com/in/leonardo-pangaio
  luciana:
    name: Luciana Sampaio
    description: Engenheira de Dados
    avatar: https://github.com/luasampaio.png
    url: https://www.linkedin.com/in/luciana-sampaio/
  alberto:
    name: Alberto Sanches
    description: Especialista em DevSecOps
    avatar: https://media.licdn.com/dms/image/v2/C4D03AQHW8_1z2HSuWQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1663098322180?e=1747872000&v=beta&t=_F15eETQPDg8tTh4QeQ0xrlT69W7QN8WQyqsFzfPxcM
    url: https://www.linkedin.com/in/alberto-sanches-771482106/
  diego:
    name: Diego Costa
    description: Tech Leader
    avatar: https://media.licdn.com/dms/image/v2/C4D03AQHXOWgzNicx1w/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1524592789495?e=1749081600&v=beta&t=zguj2wm_pMz3gizRFkXo493Q71eoMbdvp-y1KeEgnnY
    url: https://www.linkedin.com/in/diego-costa-70b19839/
  leonardo-henrique:
    name: Leonardo Henrique
    description: SRE/Backend Engineer
    avatar: https://github.com/Leonardo-Henrique.png
    url: https://www.linkedin.com/in/leonardohenrique1/