name: Build
on:
  push:
    branches:
      - master 
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt

      # - name: Force Custom Domain
      #   run: echo 'pangaio.com.br' > ./CNAME

      - name: Build MKDocs site
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: mkdocs gh-deploy -v --force -f mkdocs.yml

      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          export TZ=America/Sao_Paulo
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          AUTHOR=$(git log -1 --pretty=format:"%an")
          COMMIT_HASH=$(git rev-parse HEAD)
          DATETIME=$(date +"%Y-%m-%d %H:%M:%S")

          REPO_URL="https://github.com/${{ github.repository }}"
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          COMMIT_URL="$REPO_URL/commit/$COMMIT_HASH"

          USER_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          SITE_URL="https://$USER_NAME.github.io/$REPO_NAME"

          MESSAGE="🚀 [$DATETIME] - $AUTHOR realizou um novo deploy no repositório *$REPO_NAME*!  
          📝 *Commit:* \"$COMMIT_MSG\"  
          🔗 [Ver commit no GitHub]($COMMIT_URL)
          🌎 [Veja como ficou em produção]($SITE_URL)"

          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d text="$MESSAGE" \
            -d parse_mode="Markdown"